---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: __PROJECT__-ing
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: __PROJECT__.rd.virsical.cn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: __PROJECT__
            port:
              number: 8080
  tls:
  - hosts:
    - __PROJECT__.rd.virsical.cn
    secretName: rd.virsical

