---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: __PROJECT__-work
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-dev"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
